### ISSUE TITLE
Fetching relevant data/Research papers in response to the user query and Passing to the model (Context Window issues)

### ISSUE THREAD

**Issue by IbrahimLaeeq** [Tonic-AI/scitonic#10]
We need access to good high quality that can be used to answer the user query. How would we go about identifying relevant data from the internet and then use that in our model.
1. Fetching Data 
2. Ranking data 

Also how do we decide to fetch data relevant to our user query. 

One solution would be that the user enters the websites to get the data from.

We could then scrape the articles according to their citations.

But then how shall we go about reducing the context window as we cant provide the model with multiple articles in long - form .

We could also pre-set websites for a specific domain e.g IEEE for electrical engineering etc

Also how would we reduce the API calls if we pass the articles by chunking them down by separating  a 10k word article into 1000 word chunks becuase we have to ensure that our "Research Agent" also improves its generated articles so that would also require a lot of API calls.

One solution would be to identify the relevant things from an Research article and pass that as context to the model instead of passing the whole article.

Maybe we could use a Llamapack from Llama for specific subjects i.e. Physics or Engineering and then use that model.(But this defeats the purpose of a Research Agent becuase ChatGPT and other LLMs are already trained on Research Data the main thing that we are trying to acheive is to fetch data in real time and then generate a Research Article on that)

**Comment by AAbbhishekk** [comment]
Arxiv api calls can also be helpful

**Comment by Vaishakgkumar** [comment]
we can use this video as refrence for @AAbbhishekk idea
