### ISSUE TITLE
create agentics flow / autogen group chat

### ISSUE THREAD

**Issue by Josephrp** [Tonic-AI/scitonic#4]
currently the application uses autogen and semantic-kernel, but we can use the taskweaver sql plugin , perhaps some guidance on committing to using autogen as an orchestrator, then keep the group chat simple, preferring to use semantic-kernel or taskweaver for secure application threads / plugins.

**Comment by AAbbhishekk** [comment]
May try
1. Conversational agent
2. RetrieveUserProxyAgent

**Comment by Josephrp** [comment]
some ideas : 

- [agentchat_lmm_llava.ipynb](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_lmm_llava.ipynb) , local model deployment
- [agentchat_qdrant_RetrieveChat.ipynb](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_qdrant_RetrieveChat.ipynb) , using Qdrant
- [agentchat_lmm_gpt-4v.ipynb](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_lmm_gpt-4v.ipynb) , vision llm which is a requirement

@AAbbhishekk @Kashaf212

**Comment by Josephrp** [comment]
from Sonichi :

Here is how retrieve chat works:
The message from raguserproxyagent to assistant is the retrieved document.
The message from assistant to ragproxyagent is the answer based on the retrieved doc.
